version: '3'

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight port
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--requirepass redispassword

volumes:
  redis_data:
